name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install general dependencies
      run: sudo apt install -y autoconf pkgconf cmake clang build-essential
    - name: Install LibELF for LibBPF (AF_XDP)
      run: sudo apt install -y libelf-dev 
    - name: Build JSON-C
      run: make jsonc
    - name: Install JSON-C
      run: sudo make jsonc_install
    - name: Build LibBPF
      run: make libbpf
    - name: Build main
      run: make
    - name: Install main
      run: sudo make install
    - name: Store build artifacts
      uses: actions/upload-artifact@master
      with:
        name: build-output
        path: build/pcktbatch
